services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "4080:4080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepassword
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
