apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
  labels:
    app: backend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 4080
          env:
            - name: NODE_ENV
              value: "{{ .Values.frontend.env.NODE_ENV }}"
