apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: mern-app
spec:
  secretName: tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - MERN App
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - visheshresume.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
