frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: bb6adbd22ae49807a00a00204bdb135227ab2881
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: bb6adbd22ae49807a00a00204bdb135227ab2881
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
