frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: latest
  env:
    NODE_ENV: "https://thetodolist.site/api"

backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: latest
  env:
    NODE_ENV: "production"

ingress:
  host: thetodolist.site
