frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: 80762168643ee3e142848877122f616511611ece
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: 80762168643ee3e142848877122f616511611ece
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
