frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: 7924cca76386f5ba6b74ee5a43b0317741afa005
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: 7924cca76386f5ba6b74ee5a43b0317741afa005
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
