frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: bd0bc52e8d0973a8ef6cb06f23cdaeeda781a56f
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: bd0bc52e8d0973a8ef6cb06f23cdaeeda781a56f
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
