frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: 89c4b32ec29242b59f1112bd7a2dcac8ce5f3e11
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: 89c4b32ec29242b59f1112bd7a2dcac8ce5f3e11
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
