frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: 0bbb63c759679701c1c9c2b5c66b1934b45c3686
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: 0bbb63c759679701c1c9c2b5c66b1934b45c3686
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
