frontend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: 4c4fc3ec6fd229973d2747431afbcc52fd016776
  env:
    NODE_ENV: "https://thetodolist.site/api"
backend:
  replicas: 2
  image:
    repository: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: 4c4fc3ec6fd229973d2747431afbcc52fd016776
  env:
    NODE_ENV: "production"
ingress:
  host: thetodolist.site
