apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 533267410454.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
            - containerPort: 4080
          env:
            - name: NODE_ENV
              value: "production"

            - name: MONGODB_URI
              valueFrom:
                secretRef:
                  name: mongodb-secret
                  key: uri